version: '3'

services:
  node1:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu

  node2:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
      
  node3:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
      
  node4:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
      