FROM ubuntu:14.04
MAINTAINER Surya Tresna <surya.tresna@gmail.com>

ENV DEBIAN_FRONTEND noninteractive
RUN mkdir -p /etc/apt /var/run
RUN groupadd ubuntu
RUN useradd -g ubuntu -G sudo ubuntu
RUN usermod --password rahasia ubuntu
RUN echo ubuntu:u | chpasswd
RUN cp -a /etc/skel /home/ubuntu
RUN chown -R ubuntu.ubuntu /home/ubuntu
RUN ln -sf /proc/mounts /etc/mtab
RUN echo "ubuntu ALL=(ALL:ALL) NOPASSWD: ALL" > /etc/sudoers.d/ubuntu


RUN mkdir /home/ubuntu/.ssh
RUN chown ubuntu.ubuntu /home/ubuntu/.ssh
RUN chmod 700 /home/ubuntu/.ssh
RUN echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDNicDKOqTr5zVlnDF5HyEgh9G0U2t07K91fs/Hs3nf5XUKfTMvnlW8aPwkuySGbk/2fORer8gLh90HuEX7xoD6RQ9qax7yW2JiR/i7vR+1Qby/jI7pUYHtkyV0g/InaK42FQAL1ur9Kqpg+f2nqSBRVMZMyAGiphuj3371NLhdTE3fvhsilAf+GIvct9BqW3GxTZVtn6vGY58QMJ1lrHd2KeX+/S6MhdZJHWm2FF///PzuDEqlewaLn32QYjx2de8zjfiy1VJjaB3766hDyIELSzYbkSg1/TjInlRQkYGB4UcTTpGSioYsVc3XTeL/PyAZ3FJUfYW/ls0DAxZRAJtR surya.agung@tokopedia.com" >> /home/ubuntu/.ssh/authorized_keys

ENV HOME /home/ubuntu
EXPOSE 22 389 636 3306

ENTRYPOINT exec /sbin/init --startup-event=failsafe-boot